name: Analysis & Deployment
on:
  workflow_run:
    workflows: ["CI/CD"]
    types: 
       - completed

jobs:
  Analyze:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: variable
        id: env
        run: |
          
          echo "::set-output name=url::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "::set-output name=num::$GITHUB_RUN_NUMBER"
          echo "::set-output name=ci::$CI"
          echo "::set-output name=date::$(date +%s)"
          echo "::set-output name=approvedate::$(date +'%Y-%m-%dT%H:%M:%S')"
      
      - name: Build and analyze
        id: tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=http://13.82.226.119:9000/sonar  -Dsonar.login=0509856fd81ea530443388a7a684302db0c31327 -Dsonar.projectKey=SpringBootHelloWorld
          
      - name: call Adopt-Analyze API
        if: always()
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://52.188.21.117:8012/adopt-services/codeanalysis'
          method: 'POST'
          contentType: application/json
          data: '{ "buildDisplayName": "github.${{ github.event.workflow_run.run_number }}", "buildURL": "${{ steps.env.outputs.url }}","projectId": 59, "sonarKey": "0509856fd81ea530443388a7a684302db0c31327" }'

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          
          SLACK_MESSAGE: Sonar analysis completed.you can find the results at:http://13.82.226.119:9000/sonar/dashboard?id=SpringBootHelloWorld
          SLACK_TITLE: Code Analysis
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  Deployment:
    #needs: [Analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: variable
        id: env
        run: |
          
          echo "::set-output name=url::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          #echo "::set-output name=num::${{ github.event.workflow_run.run_number }}"
          echo "::set-output name=ci::$CI"
          echo "::set-output name=date::$(date +%s)"
          echo "::set-output name=approvedate::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Run script
        run: |
          chmod +x ./deployment.sh
          ./deployment.sh
      - name: Run one-line script
        id: deploy
        run: 
           echo "::set-output name=op::$(wget -O /dev/null http://localhost:8080/employee 2>&1 | grep -o "200")"

      - name: run notify
        id: ok
        if: steps.deploy.outputs.op == 'true'
        run: |
          echo "::set-output name=status::${{ job.status == 'success'}}"   
     
      - name: run notify
        id: notok
       # if: steps.deploy.outputs.op != 'true'
        run: |
          echo "::set-output name=status::${{ job.status == 'failure'}}"                   

        
      - uses: rtCamp/action-slack-notify@v2
        if: always()
          
        env:
          
          SLACK_MESSAGE: HTTP- ${{ steps.deploy.outputs.op }}
          SLACK_TITLE: Deployment status
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
     

      - name: call Adopt-Deployment API
        if: steps.deploy.outputs.op == 'true'
        uses: fjogeleit/http-request-action@v1
       
        with:
          url: 'http://52.188.21.117:8012/adopt-services/devdeployment/save'
          method: 'POST'
          contentType: application/json
          data: '{"buildNumber": "${{ github.event.workflow_run.run_number }}","deployedDate": "${{ steps.env.outputs.approvedate}}","deploymentStatus": ${{ steps.ok.outputs.status }},"environment": "DEV","projectId": 59,"projectName": "SpringBootHelloWorld"}'
      
      - name: run notok notify
        if: steps.deploy.outputs.op != 'true'
        id: notok
        run: |
          echo "::set-output name=status::${{ job.status == 'failure'}}"                   
          
      - uses: rtCamp/action-slack-notify@v2
        if: always()
          
        env:
          
          SLACK_MESSAGE: HTTP- ${{ steps.notok.outputs.status }}
          SLACK_TITLE: Deployment status
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    
      - name: call Adopt-Deployment API
        if: steps.deploy.outputs.op != 'true'
        uses: fjogeleit/http-request-action@v1
       
        with:
          url: 'http://52.188.21.117:8012/adopt-services/devdeployment/save'
          method: 'POST'
          contentType: application/json
          data: '{"buildNumber": "${{ github.event.workflow_run.run_number }}","deployedDate": "${{ steps.env.outputs.approvedate}}","deploymentStatus": ${{ steps.notok.outputs.status }},"environment": "DEV","projectId": 59,"projectName": "SpringBootHelloWorld"}'

      

      

      
      
      
