name: CI build
on:
  push:
    branches:
      - master
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - name: Set date to IST
        run: |
          sudo unlink /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
          
      - name: variable
        id: env
        run: |
          
          echo "::set-output name=url::$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "::set-output name=num::$GITHUB_RUN_NUMBER"
          echo "::set-output name=ci::$CI"
          echo "::set-output name=date::$(($(date +%s%N)/1000000))"
      - name: Maven build and deploy
        id: buildstatus
        run: |
          mavn clean test
          #mvn clean deploy
        continue-on-error: true
      - name: call API
        if: job.steps.buildstatus.status == failure() 
        env: 
          CI: false
        uses: fjogeleit/http-request-action@v1
        with:
            url: 'http://52.188.21.117:8012/adopt-services/build'
            method: 'POST'
            contentType: application/json
            data: '{ "buildDisplayName": "github.${{ steps.env.outputs.num }}", "buildDuration": "00:00:56", "buildStartDate": ${{ steps.env.outputs.date }}, "buildStatus": "${CI}", "buildURL": "${{ steps.env.outputs.url }}",  "projectId": 59 }'
        
  
      - name: Slack Notification 
        uses: rtCamp/action-slack-notify@v2
        env:
          
          SLACK_MESSAGE: Build ${{ steps.env.outputs.num }} completed
          SLACK_TITLE: CI Test Suite
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
      
          
    #  - name: call API
    #    uses: fjogeleit/http-request-action@v1
     #   with:
      #    url: 'http://52.188.21.117:8012/adopt-services/build'
       #   method: 'POST'
        #  contentType: application/json
         # data: '{ "buildDisplayName": "github.${{ steps.env.outputs.num }}", "buildDuration": "00:00:56", "buildStartDate": ${{ steps.env.outputs.date }}, "buildStatus": ${{ steps.env.outputs.ci }}, "buildURL": "${{ steps.env.outputs.url }}",  "projectId": 59 }'
 
