name: CI build
on:
  push:
    branches:
      - master
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/checkout@v2
      - name: Maven build and deploy
        id: do-stuff
        run: |
          mvn clean test
          #mvn clean deploy
      - uses: rtCamp/action-slack-notify@v2
        env:
          
          SLACK_MESSAGE: ${{ steps.do-stuff.outputs.response }} 
          SLACK_TITLE: CI Test Suite
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           
      
      - name: call API
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://52.188.21.117:8012/adopt-services/codeanalysis'
          method: 'POST'
          #contentType: application/json
          #data: '{ "property": ["Sites"], "report_type" : ["ALL"] }'   
         

                         
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}
        
