name: CI build
on:
  push:
    branches:
      - master
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/checkout@v2
      - name: current date
        id: date
        run: |
          sudo unlink /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
          echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Maven build and deploy
        id: do-stuff
        run: |
          mvn clean test
          #mvn clean deploy
      - uses: rtCamp/action-slack-notify@v2
        env:
          
          SLACK_MESSAGE: ${{ steps.do-stuff.outputs.response }} 
          SLACK_TITLE: CI Test Suite
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           
      #- name: Env variables
       # run: |
       #   echo "url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
        
        #  echo "run=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
         # echo "ci=$CI" >> $GITHUB_ENV
          
      - name: call API
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://52.188.21.117:8012/adopt-services/build'
          method: 'POST'
          contentType: application/json
          data: '{ "buildDisplayName": ${GITHUB_RUN_NUMBER}, "buildDuration": "00:00:56", "buildStartDate": ${{ steps.date.outputs.date }}, "buildStatus": ${CI}  "buildURL": "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}",  "projectId": 59 }'
         

                         
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}
        
